// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: kinnekode/restaurant/test/test2.proto

package test

import (
	document "github.com/kinneko-de/test-api-contract/golang/kinnekode/document"
	protobuf "github.com/kinneko-de/test-api-contract/golang/kinnekode/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *protobuf.Uuid       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurant *document.Restaurant `protobuf:"bytes,2,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_test_test2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_test_test2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_test_test2_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetId() *protobuf.Uuid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Test) GetRestaurant() *document.Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

var File_kinnekode_restaurant_test_test2_proto protoreflect.FileDescriptor

var file_kinnekode_restaurant_test_test2_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x24, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69,
	0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x40, 0x0a, 0x0a, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x42, 0x48, 0x5a, 0x46, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x69,
	0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_restaurant_test_test2_proto_rawDescOnce sync.Once
	file_kinnekode_restaurant_test_test2_proto_rawDescData = file_kinnekode_restaurant_test_test2_proto_rawDesc
)

func file_kinnekode_restaurant_test_test2_proto_rawDescGZIP() []byte {
	file_kinnekode_restaurant_test_test2_proto_rawDescOnce.Do(func() {
		file_kinnekode_restaurant_test_test2_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_restaurant_test_test2_proto_rawDescData)
	})
	return file_kinnekode_restaurant_test_test2_proto_rawDescData
}

var file_kinnekode_restaurant_test_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kinnekode_restaurant_test_test2_proto_goTypes = []interface{}{
	(*Test)(nil),                // 0: kinnekode.restaurant.test.Test
	(*protobuf.Uuid)(nil),       // 1: kinnekode.protobuf.Uuid
	(*document.Restaurant)(nil), // 2: kinnekode.restaurant.Restaurant
}
var file_kinnekode_restaurant_test_test2_proto_depIdxs = []int32{
	1, // 0: kinnekode.restaurant.test.Test.id:type_name -> kinnekode.protobuf.Uuid
	2, // 1: kinnekode.restaurant.test.Test.restaurant:type_name -> kinnekode.restaurant.Restaurant
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kinnekode_restaurant_test_test2_proto_init() }
func file_kinnekode_restaurant_test_test2_proto_init() {
	if File_kinnekode_restaurant_test_test2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_restaurant_test_test2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_restaurant_test_test2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kinnekode_restaurant_test_test2_proto_goTypes,
		DependencyIndexes: file_kinnekode_restaurant_test_test2_proto_depIdxs,
		MessageInfos:      file_kinnekode_restaurant_test_test2_proto_msgTypes,
	}.Build()
	File_kinnekode_restaurant_test_test2_proto = out.File
	file_kinnekode_restaurant_test_test2_proto_rawDesc = nil
	file_kinnekode_restaurant_test_test2_proto_goTypes = nil
	file_kinnekode_restaurant_test_test2_proto_depIdxs = nil
}
