// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: kinnekode/restaurant/document/generate_document.proto

package document

import (
	protobuf "github.com/kinneko-de/test-api-contract/golang/kinnekode/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateDocumentV1_Document_OutputFormat int32

const (
	GenerateDocumentV1_Document_OUTPUT_FORMAT_UNSPECIFIED GenerateDocumentV1_Document_OutputFormat = 0
	GenerateDocumentV1_Document_OUTPUT_FORMAT_PDF         GenerateDocumentV1_Document_OutputFormat = 1
)

// Enum value maps for GenerateDocumentV1_Document_OutputFormat.
var (
	GenerateDocumentV1_Document_OutputFormat_name = map[int32]string{
		0: "OUTPUT_FORMAT_UNSPECIFIED",
		1: "OUTPUT_FORMAT_PDF",
	}
	GenerateDocumentV1_Document_OutputFormat_value = map[string]int32{
		"OUTPUT_FORMAT_UNSPECIFIED": 0,
		"OUTPUT_FORMAT_PDF":         1,
	}
)

func (x GenerateDocumentV1_Document_OutputFormat) Enum() *GenerateDocumentV1_Document_OutputFormat {
	p := new(GenerateDocumentV1_Document_OutputFormat)
	*p = x
	return p
}

func (x GenerateDocumentV1_Document_OutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateDocumentV1_Document_OutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_kinnekode_restaurant_document_generate_document_proto_enumTypes[0].Descriptor()
}

func (GenerateDocumentV1_Document_OutputFormat) Type() protoreflect.EnumType {
	return &file_kinnekode_restaurant_document_generate_document_proto_enumTypes[0]
}

func (x GenerateDocumentV1_Document_OutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateDocumentV1_Document_OutputFormat.Descriptor instead.
func (GenerateDocumentV1_Document_OutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP(), []int{0, 0, 0}
}

type GenerateDocumentV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId          *protobuf.Uuid                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestedDocuments []*GenerateDocumentV1_Document `protobuf:"bytes,2,rep,name=requested_documents,json=requestedDocuments,proto3" json:"requested_documents,omitempty"`
}

func (x *GenerateDocumentV1) Reset() {
	*x = GenerateDocumentV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDocumentV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentV1) ProtoMessage() {}

func (x *GenerateDocumentV1) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentV1.ProtoReflect.Descriptor instead.
func (*GenerateDocumentV1) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDocumentV1) GetRequestId() *protobuf.Uuid {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *GenerateDocumentV1) GetRequestedDocuments() []*GenerateDocumentV1_Document {
	if x != nil {
		return x.RequestedDocuments
	}
	return nil
}

type GenerateDocumentV1_Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputFormats []GenerateDocumentV1_Document_OutputFormat `protobuf:"varint,1,rep,packed,name=output_formats,json=outputFormats,proto3,enum=kinnekode.restaurant.document.GenerateDocumentV1_Document_OutputFormat" json:"output_formats,omitempty"`
	// Types that are assignable to Type:
	//
	//	*GenerateDocumentV1_Document_Invoice
	Type isGenerateDocumentV1_Document_Type `protobuf_oneof:"type"`
}

func (x *GenerateDocumentV1_Document) Reset() {
	*x = GenerateDocumentV1_Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDocumentV1_Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentV1_Document) ProtoMessage() {}

func (x *GenerateDocumentV1_Document) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentV1_Document.ProtoReflect.Descriptor instead.
func (*GenerateDocumentV1_Document) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GenerateDocumentV1_Document) GetOutputFormats() []GenerateDocumentV1_Document_OutputFormat {
	if x != nil {
		return x.OutputFormats
	}
	return nil
}

func (m *GenerateDocumentV1_Document) GetType() isGenerateDocumentV1_Document_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *GenerateDocumentV1_Document) GetInvoice() *GenerateDocumentV1_Document_InvoiceV1 {
	if x, ok := x.GetType().(*GenerateDocumentV1_Document_Invoice); ok {
		return x.Invoice
	}
	return nil
}

type isGenerateDocumentV1_Document_Type interface {
	isGenerateDocumentV1_Document_Type()
}

type GenerateDocumentV1_Document_Invoice struct {
	Invoice *GenerateDocumentV1_Document_InvoiceV1 `protobuf:"bytes,4,opt,name=invoice,proto3,oneof"`
}

func (*GenerateDocumentV1_Document_Invoice) isGenerateDocumentV1_Document_Type() {}

type GenerateDocumentV1_Document_InvoiceV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveredOn *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=delivered_on,json=deliveredOn,proto3" json:"delivered_on,omitempty"`
	// three character currency code as specified in ISO 4217 ( see https://de.wikipedia.org/wiki/ISO_4217 )
	CurrencyCode string                                           `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Recipient    *GenerateDocumentV1_Document_InvoiceV1_Recipient `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Items        []*GenerateDocumentV1_Document_InvoiceV1_Item    `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GenerateDocumentV1_Document_InvoiceV1) Reset() {
	*x = GenerateDocumentV1_Document_InvoiceV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDocumentV1_Document_InvoiceV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentV1_Document_InvoiceV1) ProtoMessage() {}

func (x *GenerateDocumentV1_Document_InvoiceV1) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentV1_Document_InvoiceV1.ProtoReflect.Descriptor instead.
func (*GenerateDocumentV1_Document_InvoiceV1) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GenerateDocumentV1_Document_InvoiceV1) GetDeliveredOn() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredOn
	}
	return nil
}

func (x *GenerateDocumentV1_Document_InvoiceV1) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *GenerateDocumentV1_Document_InvoiceV1) GetRecipient() *GenerateDocumentV1_Document_InvoiceV1_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *GenerateDocumentV1_Document_InvoiceV1) GetItems() []*GenerateDocumentV1_Document_InvoiceV1_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GenerateDocumentV1_Document_InvoiceV1_Recipient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Street   string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	PostCode string `protobuf:"bytes,4,opt,name=postCode,proto3" json:"postCode,omitempty"`
	Country  string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) Reset() {
	*x = GenerateDocumentV1_Document_InvoiceV1_Recipient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentV1_Document_InvoiceV1_Recipient) ProtoMessage() {}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentV1_Document_InvoiceV1_Recipient.ProtoReflect.Descriptor instead.
func (*GenerateDocumentV1_Document_InvoiceV1_Recipient) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Recipient) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GenerateDocumentV1_Document_InvoiceV1_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string            `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Quantity    int64             `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	NetAmount   *protobuf.Decimal `protobuf:"bytes,3,opt,name=netAmount,proto3" json:"netAmount,omitempty"`
	Taxation    *protobuf.Decimal `protobuf:"bytes,4,opt,name=taxation,proto3" json:"taxation,omitempty"`
	TotalAmount *protobuf.Decimal `protobuf:"bytes,5,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Sum         *protobuf.Decimal `protobuf:"bytes,6,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) Reset() {
	*x = GenerateDocumentV1_Document_InvoiceV1_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentV1_Document_InvoiceV1_Item) ProtoMessage() {}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_generate_document_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentV1_Document_InvoiceV1_Item.ProtoReflect.Descriptor instead.
func (*GenerateDocumentV1_Document_InvoiceV1_Item) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) GetNetAmount() *protobuf.Decimal {
	if x != nil {
		return x.NetAmount
	}
	return nil
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) GetTaxation() *protobuf.Decimal {
	if x != nil {
		return x.Taxation
	}
	return nil
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) GetTotalAmount() *protobuf.Decimal {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *GenerateDocumentV1_Document_InvoiceV1_Item) GetSum() *protobuf.Decimal {
	if x != nil {
		return x.Sum
	}
	return nil
}

var File_kinnekode_restaurant_document_generate_document_proto protoreflect.FileDescriptor

var file_kinnekode_restaurant_document_generate_document_proto_rawDesc = []byte{
	0x0a, 0x35, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x63, 0x69,
	0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65,
	0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x75,
	0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x09, 0x0a, 0x12, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x12,
	0x37, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x6b, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64,
	0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x98, 0x08, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x6e, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x47, 0x2e, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x2e, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x52, 0x0d, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x73, 0x12, 0x60, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x56, 0x31, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x1a, 0xeb, 0x05, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x56, 0x31, 0x12, 0x3d, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x5f,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x4f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x6c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4e, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x2e, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x56, 0x31, 0x2e,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x5f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x49, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x56, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x81, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0xa6, 0x02, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x39, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x52, 0x09, 0x6e, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x74,
	0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x08, 0x74, 0x61, 0x78, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x03, 0x73,
	0x75, 0x6d, 0x22, 0x44, 0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x1d, 0x0a, 0x19, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x5f, 0x46, 0x4f, 0x52,
	0x4d, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d,
	0x41, 0x54, 0x5f, 0x50, 0x44, 0x46, 0x10, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x61,
	0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_restaurant_document_generate_document_proto_rawDescOnce sync.Once
	file_kinnekode_restaurant_document_generate_document_proto_rawDescData = file_kinnekode_restaurant_document_generate_document_proto_rawDesc
)

func file_kinnekode_restaurant_document_generate_document_proto_rawDescGZIP() []byte {
	file_kinnekode_restaurant_document_generate_document_proto_rawDescOnce.Do(func() {
		file_kinnekode_restaurant_document_generate_document_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_restaurant_document_generate_document_proto_rawDescData)
	})
	return file_kinnekode_restaurant_document_generate_document_proto_rawDescData
}

var file_kinnekode_restaurant_document_generate_document_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kinnekode_restaurant_document_generate_document_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kinnekode_restaurant_document_generate_document_proto_goTypes = []interface{}{
	(GenerateDocumentV1_Document_OutputFormat)(0),           // 0: kinnekode.restaurant.document.GenerateDocumentV1.Document.OutputFormat
	(*GenerateDocumentV1)(nil),                              // 1: kinnekode.restaurant.document.GenerateDocumentV1
	(*GenerateDocumentV1_Document)(nil),                     // 2: kinnekode.restaurant.document.GenerateDocumentV1.Document
	(*GenerateDocumentV1_Document_InvoiceV1)(nil),           // 3: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1
	(*GenerateDocumentV1_Document_InvoiceV1_Recipient)(nil), // 4: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Recipient
	(*GenerateDocumentV1_Document_InvoiceV1_Item)(nil),      // 5: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Item
	(*protobuf.Uuid)(nil),                                   // 6: kinnekode.protobuf.Uuid
	(*timestamppb.Timestamp)(nil),                           // 7: google.protobuf.Timestamp
	(*protobuf.Decimal)(nil),                                // 8: kinnekode.protobuf.Decimal
}
var file_kinnekode_restaurant_document_generate_document_proto_depIdxs = []int32{
	6,  // 0: kinnekode.restaurant.document.GenerateDocumentV1.request_id:type_name -> kinnekode.protobuf.Uuid
	2,  // 1: kinnekode.restaurant.document.GenerateDocumentV1.requested_documents:type_name -> kinnekode.restaurant.document.GenerateDocumentV1.Document
	0,  // 2: kinnekode.restaurant.document.GenerateDocumentV1.Document.output_formats:type_name -> kinnekode.restaurant.document.GenerateDocumentV1.Document.OutputFormat
	3,  // 3: kinnekode.restaurant.document.GenerateDocumentV1.Document.invoice:type_name -> kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1
	7,  // 4: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.delivered_on:type_name -> google.protobuf.Timestamp
	4,  // 5: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.recipient:type_name -> kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Recipient
	5,  // 6: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.items:type_name -> kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Item
	8,  // 7: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Item.netAmount:type_name -> kinnekode.protobuf.Decimal
	8,  // 8: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Item.taxation:type_name -> kinnekode.protobuf.Decimal
	8,  // 9: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Item.totalAmount:type_name -> kinnekode.protobuf.Decimal
	8,  // 10: kinnekode.restaurant.document.GenerateDocumentV1.Document.InvoiceV1.Item.sum:type_name -> kinnekode.protobuf.Decimal
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_kinnekode_restaurant_document_generate_document_proto_init() }
func file_kinnekode_restaurant_document_generate_document_proto_init() {
	if File_kinnekode_restaurant_document_generate_document_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_restaurant_document_generate_document_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDocumentV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_generate_document_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDocumentV1_Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_generate_document_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDocumentV1_Document_InvoiceV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_generate_document_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDocumentV1_Document_InvoiceV1_Recipient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_generate_document_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDocumentV1_Document_InvoiceV1_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_restaurant_document_generate_document_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GenerateDocumentV1_Document_Invoice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_restaurant_document_generate_document_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kinnekode_restaurant_document_generate_document_proto_goTypes,
		DependencyIndexes: file_kinnekode_restaurant_document_generate_document_proto_depIdxs,
		EnumInfos:         file_kinnekode_restaurant_document_generate_document_proto_enumTypes,
		MessageInfos:      file_kinnekode_restaurant_document_generate_document_proto_msgTypes,
	}.Build()
	File_kinnekode_restaurant_document_generate_document_proto = out.File
	file_kinnekode_restaurant_document_generate_document_proto_rawDesc = nil
	file_kinnekode_restaurant_document_generate_document_proto_goTypes = nil
	file_kinnekode_restaurant_document_generate_document_proto_depIdxs = nil
}
