// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: kinnekode/apicontract/document/grpc/v1/document_service.proto

package v1

import (
	protobuf "github.com/kinneko-de/test-api-contract/golang/kinnekode/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadDocumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*UploadDocumentRequest_Metadata_
	//	*UploadDocumentRequest_Payload_
	Content isUploadDocumentRequest_Content `protobuf_oneof:"content"`
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{0}
}

func (m *UploadDocumentRequest) GetContent() isUploadDocumentRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *UploadDocumentRequest) GetMetadata() *UploadDocumentRequest_Metadata {
	if x, ok := x.GetContent().(*UploadDocumentRequest_Metadata_); ok {
		return x.Metadata
	}
	return nil
}

func (x *UploadDocumentRequest) GetPayload() *UploadDocumentRequest_Payload {
	if x, ok := x.GetContent().(*UploadDocumentRequest_Payload_); ok {
		return x.Payload
	}
	return nil
}

type isUploadDocumentRequest_Content interface {
	isUploadDocumentRequest_Content()
}

type UploadDocumentRequest_Metadata_ struct {
	Metadata *UploadDocumentRequest_Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadDocumentRequest_Payload_ struct {
	Payload *UploadDocumentRequest_Payload `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*UploadDocumentRequest_Metadata_) isUploadDocumentRequest_Content() {}

func (*UploadDocumentRequest_Payload_) isUploadDocumentRequest_Content() {}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId *protobuf.Uuid `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocumentResponse) GetDocumentId() *protobuf.Uuid {
	if x != nil {
		return x.DocumentId
	}
	return nil
}

type DownloadDocumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownloadDocumentRequest) Reset() {
	*x = DownloadDocumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentRequest) ProtoMessage() {}

func (x *DownloadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentRequest.ProtoReflect.Descriptor instead.
func (*DownloadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{2}
}

type DownloadDocumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownloadDocumentResponse) Reset() {
	*x = DownloadDocumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentResponse) ProtoMessage() {}

func (x *DownloadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentResponse.ProtoReflect.Descriptor instead.
func (*DownloadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{3}
}

type UploadDocumentRequest_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *UploadDocumentRequest_Metadata) Reset() {
	*x = UploadDocumentRequest_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentRequest_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest_Metadata) ProtoMessage() {}

func (x *UploadDocumentRequest_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest_Metadata.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest_Metadata) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UploadDocumentRequest_Metadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadDocumentRequest_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileChunk []byte `protobuf:"bytes,1,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
}

func (x *UploadDocumentRequest_Payload) Reset() {
	*x = UploadDocumentRequest_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentRequest_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest_Payload) ProtoMessage() {}

func (x *UploadDocumentRequest_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest_Payload.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest_Payload) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UploadDocumentRequest_Payload) GetFileChunk() []byte {
	if x != nil {
		return x.FileChunk
	}
	return nil
}

var File_kinnekode_apicontract_document_grpc_v1_document_service_proto protoreflect.FileDescriptor

var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x26, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x75, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x02, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x64, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x46, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x61, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x27, 0x0a, 0x08, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x1a, 0x28, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x09, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x16, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x75, 0x69, 0x64,
	0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xbf, 0x02, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x91, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x2e, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x97, 0x01, 0x0a, 0x10,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x3f, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x40, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescOnce sync.Once
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData = file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc
)

func file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP() []byte {
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescOnce.Do(func() {
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData)
	})
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData
}

var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_goTypes = []interface{}{
	(*UploadDocumentRequest)(nil),          // 0: kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),         // 1: kinnekode.apicontract.document.grpc.v1.UploadDocumentResponse
	(*DownloadDocumentRequest)(nil),        // 2: kinnekode.apicontract.document.grpc.v1.DownloadDocumentRequest
	(*DownloadDocumentResponse)(nil),       // 3: kinnekode.apicontract.document.grpc.v1.DownloadDocumentResponse
	(*UploadDocumentRequest_Metadata)(nil), // 4: kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest.Metadata
	(*UploadDocumentRequest_Payload)(nil),  // 5: kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest.Payload
	(*protobuf.Uuid)(nil),                  // 6: kinnekode.protobuf.Uuid
}
var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_depIdxs = []int32{
	4, // 0: kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest.metadata:type_name -> kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest.Metadata
	5, // 1: kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest.payload:type_name -> kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest.Payload
	6, // 2: kinnekode.apicontract.document.grpc.v1.UploadDocumentResponse.document_id:type_name -> kinnekode.protobuf.Uuid
	0, // 3: kinnekode.apicontract.document.grpc.v1.DocumentService.UploadDocument:input_type -> kinnekode.apicontract.document.grpc.v1.UploadDocumentRequest
	2, // 4: kinnekode.apicontract.document.grpc.v1.DocumentService.DownloadDocument:input_type -> kinnekode.apicontract.document.grpc.v1.DownloadDocumentRequest
	1, // 5: kinnekode.apicontract.document.grpc.v1.DocumentService.UploadDocument:output_type -> kinnekode.apicontract.document.grpc.v1.UploadDocumentResponse
	3, // 6: kinnekode.apicontract.document.grpc.v1.DocumentService.DownloadDocument:output_type -> kinnekode.apicontract.document.grpc.v1.DownloadDocumentResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kinnekode_apicontract_document_grpc_v1_document_service_proto_init() }
func file_kinnekode_apicontract_document_grpc_v1_document_service_proto_init() {
	if File_kinnekode_apicontract_document_grpc_v1_document_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadDocumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadDocumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentRequest_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentRequest_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UploadDocumentRequest_Metadata_)(nil),
		(*UploadDocumentRequest_Payload_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kinnekode_apicontract_document_grpc_v1_document_service_proto_goTypes,
		DependencyIndexes: file_kinnekode_apicontract_document_grpc_v1_document_service_proto_depIdxs,
		MessageInfos:      file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes,
	}.Build()
	File_kinnekode_apicontract_document_grpc_v1_document_service_proto = out.File
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc = nil
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_goTypes = nil
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_depIdxs = nil
}
