// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: kinnekode/apicontract/document/grpc/v1/document_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadRequest:
	//
	//	*StartUploadRequest_FileMetadata
	//	*StartUploadRequest_FilePayload
	UploadRequest isStartUploadRequest_UploadRequest `protobuf_oneof:"upload_request"`
}

func (x *StartUploadRequest) Reset() {
	*x = StartUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUploadRequest) ProtoMessage() {}

func (x *StartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUploadRequest.ProtoReflect.Descriptor instead.
func (*StartUploadRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{0}
}

func (m *StartUploadRequest) GetUploadRequest() isStartUploadRequest_UploadRequest {
	if m != nil {
		return m.UploadRequest
	}
	return nil
}

func (x *StartUploadRequest) GetFileMetadata() *FileMetadata {
	if x, ok := x.GetUploadRequest().(*StartUploadRequest_FileMetadata); ok {
		return x.FileMetadata
	}
	return nil
}

func (x *StartUploadRequest) GetFilePayload() *FilePayload {
	if x, ok := x.GetUploadRequest().(*StartUploadRequest_FilePayload); ok {
		return x.FilePayload
	}
	return nil
}

type isStartUploadRequest_UploadRequest interface {
	isStartUploadRequest_UploadRequest()
}

type StartUploadRequest_FileMetadata struct {
	FileMetadata *FileMetadata `protobuf:"bytes,1,opt,name=file_metadata,json=fileMetadata,proto3,oneof"`
}

type StartUploadRequest_FilePayload struct {
	FilePayload *FilePayload `protobuf:"bytes,2,opt,name=file_payload,json=filePayload,proto3,oneof"`
}

func (*StartUploadRequest_FileMetadata) isStartUploadRequest_UploadRequest() {}

func (*StartUploadRequest_FilePayload) isStartUploadRequest_UploadRequest() {}

type StartUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartUploadResponse) Reset() {
	*x = StartUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUploadResponse) ProtoMessage() {}

func (x *StartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUploadResponse.ProtoReflect.Descriptor instead.
func (*StartUploadResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{1}
}

type StartDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartDownloadRequest) Reset() {
	*x = StartDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDownloadRequest) ProtoMessage() {}

func (x *StartDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDownloadRequest.ProtoReflect.Descriptor instead.
func (*StartDownloadRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{2}
}

type StartDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartDownloadResponse) Reset() {
	*x = StartDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDownloadResponse) ProtoMessage() {}

func (x *StartDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDownloadResponse.ProtoReflect.Descriptor instead.
func (*StartDownloadResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{3}
}

type ResumeUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeUploadRequest) Reset() {
	*x = ResumeUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeUploadRequest) ProtoMessage() {}

func (x *ResumeUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeUploadRequest.ProtoReflect.Descriptor instead.
func (*ResumeUploadRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{4}
}

type ResumeUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeUploadResponse) Reset() {
	*x = ResumeUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeUploadResponse) ProtoMessage() {}

func (x *ResumeUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeUploadResponse.ProtoReflect.Descriptor instead.
func (*ResumeUploadResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{5}
}

type ResumeDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeDownloadRequest) Reset() {
	*x = ResumeDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDownloadRequest) ProtoMessage() {}

func (x *ResumeDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDownloadRequest.ProtoReflect.Descriptor instead.
func (*ResumeDownloadRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{6}
}

type ResumeDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeDownloadResponse) Reset() {
	*x = ResumeDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDownloadResponse) ProtoMessage() {}

func (x *ResumeDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDownloadResponse.ProtoReflect.Descriptor instead.
func (*ResumeDownloadResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{7}
}

type FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{8}
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FilePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
}

func (x *FilePayload) Reset() {
	*x = FilePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePayload) ProtoMessage() {}

func (x *FilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePayload.ProtoReflect.Descriptor instead.
func (*FilePayload) Descriptor() ([]byte, []int) {
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP(), []int{9}
}

func (x *FilePayload) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_kinnekode_apicontract_document_grpc_v1_document_service_proto protoreflect.FileDescriptor

var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x26, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x22, 0xdd, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5b,
	0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0c, 0x66,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x58, 0x0a, 0x0c, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x33, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x10, 0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16,
	0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x15, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17,
	0x0a, 0x15, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2b, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x23,
	0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x32, 0xcf, 0x04, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x88, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3a, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3b, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x12, 0x8e, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3c, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x12, 0x8b, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3b, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x3c, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x12, 0x91, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3d, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescOnce sync.Once
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData = file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc
)

func file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescGZIP() []byte {
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescOnce.Do(func() {
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData)
	})
	return file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDescData
}

var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_goTypes = []interface{}{
	(*StartUploadRequest)(nil),     // 0: kinnekode.apicontract.document.grpc.v1.StartUploadRequest
	(*StartUploadResponse)(nil),    // 1: kinnekode.apicontract.document.grpc.v1.StartUploadResponse
	(*StartDownloadRequest)(nil),   // 2: kinnekode.apicontract.document.grpc.v1.StartDownloadRequest
	(*StartDownloadResponse)(nil),  // 3: kinnekode.apicontract.document.grpc.v1.StartDownloadResponse
	(*ResumeUploadRequest)(nil),    // 4: kinnekode.apicontract.document.grpc.v1.ResumeUploadRequest
	(*ResumeUploadResponse)(nil),   // 5: kinnekode.apicontract.document.grpc.v1.ResumeUploadResponse
	(*ResumeDownloadRequest)(nil),  // 6: kinnekode.apicontract.document.grpc.v1.ResumeDownloadRequest
	(*ResumeDownloadResponse)(nil), // 7: kinnekode.apicontract.document.grpc.v1.ResumeDownloadResponse
	(*FileMetadata)(nil),           // 8: kinnekode.apicontract.document.grpc.v1.FileMetadata
	(*FilePayload)(nil),            // 9: kinnekode.apicontract.document.grpc.v1.FilePayload
}
var file_kinnekode_apicontract_document_grpc_v1_document_service_proto_depIdxs = []int32{
	8, // 0: kinnekode.apicontract.document.grpc.v1.StartUploadRequest.file_metadata:type_name -> kinnekode.apicontract.document.grpc.v1.FileMetadata
	9, // 1: kinnekode.apicontract.document.grpc.v1.StartUploadRequest.file_payload:type_name -> kinnekode.apicontract.document.grpc.v1.FilePayload
	0, // 2: kinnekode.apicontract.document.grpc.v1.DocumentService.StartUpload:input_type -> kinnekode.apicontract.document.grpc.v1.StartUploadRequest
	2, // 3: kinnekode.apicontract.document.grpc.v1.DocumentService.StartDownload:input_type -> kinnekode.apicontract.document.grpc.v1.StartDownloadRequest
	4, // 4: kinnekode.apicontract.document.grpc.v1.DocumentService.ResumeUpload:input_type -> kinnekode.apicontract.document.grpc.v1.ResumeUploadRequest
	6, // 5: kinnekode.apicontract.document.grpc.v1.DocumentService.ResumeDownload:input_type -> kinnekode.apicontract.document.grpc.v1.ResumeDownloadRequest
	1, // 6: kinnekode.apicontract.document.grpc.v1.DocumentService.StartUpload:output_type -> kinnekode.apicontract.document.grpc.v1.StartUploadResponse
	3, // 7: kinnekode.apicontract.document.grpc.v1.DocumentService.StartDownload:output_type -> kinnekode.apicontract.document.grpc.v1.StartDownloadResponse
	5, // 8: kinnekode.apicontract.document.grpc.v1.DocumentService.ResumeUpload:output_type -> kinnekode.apicontract.document.grpc.v1.ResumeUploadResponse
	7, // 9: kinnekode.apicontract.document.grpc.v1.DocumentService.ResumeDownload:output_type -> kinnekode.apicontract.document.grpc.v1.ResumeDownloadResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kinnekode_apicontract_document_grpc_v1_document_service_proto_init() }
func file_kinnekode_apicontract_document_grpc_v1_document_service_proto_init() {
	if File_kinnekode_apicontract_document_grpc_v1_document_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StartUploadRequest_FileMetadata)(nil),
		(*StartUploadRequest_FilePayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kinnekode_apicontract_document_grpc_v1_document_service_proto_goTypes,
		DependencyIndexes: file_kinnekode_apicontract_document_grpc_v1_document_service_proto_depIdxs,
		MessageInfos:      file_kinnekode_apicontract_document_grpc_v1_document_service_proto_msgTypes,
	}.Build()
	File_kinnekode_apicontract_document_grpc_v1_document_service_proto = out.File
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_rawDesc = nil
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_goTypes = nil
	file_kinnekode_apicontract_document_grpc_v1_document_service_proto_depIdxs = nil
}
